# Generated by Django 4.0.5 on 2022-06-19 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bronze', 'BRONZE'), ('silver', 'SILVER'), ('gold', 'GOLD'), ('platinum', 'PLATINUM')], max_length=20)),
                ('created', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WinningPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_number', models.CharField(max_length=7)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('drawing_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winning_draw', to='lottery.drawing')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('correct_count', models.CharField(max_length=30)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('drawing_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draw_ticket', to='lottery.drawing')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ticket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, choices=[], max_length=30, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE'), ('others', 'OTHERS')], max_length=10, null=True)),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_number', models.CharField(max_length=6)),
                ('special_number', models.CharField(max_length=1)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_pick', to='lottery.ticket')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pick', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
