# Generated by Django 4.0.5 on 2022-06-20 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
