# Generated by Django 4.0.5 on 2022-06-30 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_ticket_winning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='winning',
        ),
    ]
