# Generated by Django 4.0.5 on 2022-06-24 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0005_rename_ticket_id_ticket_ticket_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='drawing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_ticket', to='lottery.drawing'),
        ),
    ]
