# Generated by Django 4.0.5 on 2022-06-30 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0005_alter_ticket_winning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winningpick',
            name='drawing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winning_draw', to='lottery.drawing'),
        ),
    ]
