# Generated by Django 4.0.5 on 2022-07-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0006_alter_winningpick_drawing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='winning_set',
            field=models.BooleanField(default=False),
        ),
    ]
