# Generated by Django 4.0.5 on 2022-07-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0007_ticket_winning_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='winning_set',
        ),
        migrations.AddField(
            model_name='drawing',
            name='winning_set',
            field=models.BooleanField(default=False),
        ),
    ]
