# Generated by Django 4.0.5 on 2022-06-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0007_alter_pick_ball_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='special_number',
            field=models.CharField(max_length=20),
        ),
    ]
