# Generated by Django 4.0.5 on 2022-07-09 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0008_remove_ticket_winning_set_drawing_winning_set'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drawing',
            options={'ordering': ('-startdate',)},
        ),
        migrations.RenameField(
            model_name='drawing',
            old_name='created',
            new_name='startdate',
        ),
        migrations.AddField(
            model_name='drawing',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
