# Generated by Django 4.0.5 on 2022-07-10 05:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0009_alter_drawing_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drawing',
            options={},
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='startdate',
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='status',
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='winning_set',
        ),
        migrations.CreateModel(
            name='Silver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('startdate', models.DateTimeField(default=datetime.datetime.now)),
                ('enddate', models.DateTimeField(default=datetime.datetime.now)),
                ('winning_set', models.BooleanField(default=False)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silver_draw', to='lottery.drawing')),
            ],
            options={
                'ordering': ('-startdate',),
            },
        ),
        migrations.CreateModel(
            name='Platinum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('startdate', models.DateTimeField(default=datetime.datetime.now)),
                ('enddate', models.DateTimeField(default=datetime.datetime.now)),
                ('winning_set', models.BooleanField(default=False)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platinum_draw', to='lottery.drawing')),
            ],
            options={
                'ordering': ('-startdate',),
            },
        ),
        migrations.CreateModel(
            name='Gold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('startdate', models.DateTimeField(default=datetime.datetime.now)),
                ('enddate', models.DateTimeField(default=datetime.datetime.now)),
                ('winning_set', models.BooleanField(default=False)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_draw', to='lottery.drawing')),
            ],
            options={
                'ordering': ('-startdate',),
            },
        ),
        migrations.CreateModel(
            name='Bronze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('startdate', models.DateTimeField(default=datetime.datetime.now)),
                ('enddate', models.DateTimeField(default=datetime.datetime.now)),
                ('winning_set', models.BooleanField(default=False)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bronze_draw', to='lottery.drawing')),
            ],
            options={
                'ordering': ('-startdate',),
            },
        ),
    ]
