# Generated by Django 4.0.5 on 2022-07-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0010_alter_drawing_options_remove_drawing_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold',
            name='enddate',
            field=models.DateTimeField(default=''),
        ),
    ]
