# Generated by Django 4.0.5 on 2022-06-27 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0010_alter_profile_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.CharField(max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='pick',
            name='ball_number',
        ),
        migrations.AlterField(
            model_name='drawing',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='pick',
            name='special_number',
            field=models.CharField(max_length=1),
        ),
        migrations.AddField(
            model_name='pick',
            name='ball_numbers',
            field=models.ManyToManyField(to='lottery.ballnumbers'),
        ),
    ]
