# Generated by Django 4.0.5 on 2022-06-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0011_ballnumbers_remove_pick_ball_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='winningpick',
            name='special_number',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='correct_count',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='winningpick',
            name='correct_number',
        ),
        migrations.AddField(
            model_name='winningpick',
            name='correct_number',
            field=models.ManyToManyField(to='lottery.ballnumbers'),
        ),
    ]
