# Generated by Django 4.0.5 on 2022-06-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0012_winningpick_special_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winningpick',
            name='special_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
