# Generated by Django 4.0.5 on 2022-06-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0013_alter_winningpick_special_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='special_number',
            field=models.CharField(max_length=10),
        ),
    ]
