# Generated by Django 4.0.5 on 2022-07-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0014_alter_drawing_options_mega_jackpot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mega',
            new_name='Megawin',
        ),
        migrations.AlterField(
            model_name='drawing',
            name='type',
            field=models.CharField(choices=[('bronze', 'BRONZE'), ('silver', 'SILVER'), ('gold', 'GOLD'), ('platinum', 'PLATINUM'), ('jackpot', 'JACKPOT'), ('megawin', 'MEGAWIN')], max_length=20),
        ),
    ]
