# Generated by Django 4.0.5 on 2022-06-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0014_alter_pick_special_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballnumbers',
            name='ball',
            field=models.CharField(max_length=20),
        ),
    ]
