# Generated by Django 4.0.5 on 2022-07-12 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0015_rename_mega_megawin_alter_drawing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='jackpot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jackpot_ticket', to='lottery.jackpot'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='megawin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='megawin_ticket', to='lottery.megawin'),
        ),
    ]
