# Generated by Django 4.0.5 on 2022-06-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0015_alter_ballnumbers_ball'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='draw_type',
            field=models.CharField(default='bronze', max_length=50),
        ),
    ]
